services:
    angular-app:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - NODE_ENV=${NODE_ENV:-production}
        container_name: app-biblioteca_angular
        ports:
            - "${APP_EXTERNAL_PORT}:80"
        restart: unless-stopped
        networks:
            - biblioteca-app-angular-network
        environment:
            - NODE_ENV=${NODE_ENV:-production}

networks:
    biblioteca-app-angular-network:
        driver: bridge
